### ISSUE TITLE
yeah no im 80 percent sure this is just broken

### ISSUE THREAD

**Issue by tinglefart445** [Lawin0129/LawinServerV2#135]
C:\Users\User1\Desktop\LawinServerV2-main>node index.js
(node:8592) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
BACKEND: App started listening on port 8080
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1912:16)
    at listenInCluster (node:net:1969:12)
    at Server.listen (node:net:2074:7)
    at Function.listen (C:\Users\User1\Desktop\LawinServerV2-main\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\User1\Desktop\LawinServerV2-main\xmpp\xmpp.js:14:41)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:524:28)
    at emitErrorNT (node:net:1948:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}

**Comment by StripperPaws** [comment]
> address already in use :::80

A program running on your pc already uses this port. Close it, or reboot your pc. Or, change the port in your Lawin config.

The backend itself is not the issue

**Comment by StripperPaws** [comment]
One thing I do recommend though. This repo is quite outdated, consider checking out Reload Backend, which is a frequently updated fork of Lawin, and has so many QOL fixes.

**Comment by kxtzownsu** [comment]
Hate to necropost but for anyone looking for the reload backend, its here [https://github.com/Project-Reload/Reload-Backend](https://github.com/Project-Reload/Reload-Backend) (correct me if i'm wrong 🙏 )
