### ISSUE TITLE
Backend crashes when users register

### ISSUE THREAD

**Issue by P3T3ROnGitHub** [Lawin0129/LawinServerV2#19]
Rarely the backend crashes when someone register an account. Here is the error code: C:\Users\csaba\desktop\BACKEND\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\csaba\desktop\BACKEND\node_modules\discord.js\src\rest\RequestHandler.js:350:13)    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\csaba\desktop\BACKEND\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply .

ps: please do it to save your settings, it's also good if it's the same every season, it's much better than not saving it at all

**Comment by Lawin0129** [comment]
Fixed
